modLoader="javafml"
loaderVersion="[${loader_version},)"
license="Mozilla Public License Version 2.0"
issueTrackerURL="https://github.com/NinjaPhenix/BetterPlacement/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="http://myurl.me/" #replace with version json in master branch of git repo
#displayURL="http://example.com/" #replace with curseforge page
authors="tterrag1098, NinjaPhenix"
description='''
Syncs block placement to cursor movement, allowing easier and faster building.
'''
[[dependencies.ninjaphenix_betterplacement]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ninjaphenix_betterplacement]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"