modLoader="javafml"
loaderVersion="[${loader_version},)"
license="Mozilla Public License Version 2.0"
issueTrackerURL="https://github.com/NinjaPhenix/PreciseBlockPlacing/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/preciseblockplacing/"
authors="tterrag1098, NinjaPhenix"
description='''
Syncs block placement to cursor movement, allowing easier and faster building.
'''
[[dependencies.preciseblockplacing]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.preciseblockplacing]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"